```yaml
name: Create Jira issue

on:
  issues:
    types:
      - opened

permissions:
  contents: write
  issues: write

jobs:
  create-issue:
    name: Create Jira issue
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main code
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0

      - name: Issue Parser
        uses: stefanbuck/github-issue-parser@v3
        id: issue-parser
        with:
          template-path: .github/ISSUE_TEMPLATE/issue-form.yml

      - name: Log Issue Parser
        run: |
          echo '${{ steps.issue-parser.outputs.issueparser_parentKey }}'
          echo '${{ steps.issue-parser.outputs.jsonString }}'

      - name: Convert markdown to Jira Syntax
        uses: peter-evans/jira2md@v1
        id: md2jira
        with:
          input-text: |
            ### Github Issue Link
            - ${{ github.event.issue.html_url }}

            ${{ github.event.issue.body }}
          mode: md2jira

      - name: Create Jira Issue
        id: create-jira
        run: |
          AUTH=$(echo -n "${{ secrets.JIRA_USER_EMAIL }}:${{ secrets.JIRA_API_TOKEN }}" | base64)

          RESPONSE=$(curl -s -X POST \
            -H "Authorization: Basic $AUTH" \
            -H "Accept: application/json" \
            -H "Content-Type: application/json" \
            ${{ secrets.JIRA_BASE_URL }}/rest/api/3/issue \
            --data "{
              \"fields\": {
                \"project\": {
                  \"key\": \"TRIP\"
                },
                \"summary\": \"${{ github.event.issue.title }}\",
                \"description\": {
                  \"type\": \"doc\",
                  \"version\": 1,
                  \"content\": [
                    {
                      \"type\": \"paragraph\",
                      \"content\": [
                        {
                          \"type\": \"text\",
                          \"text\": \"${{ github.event.issue.body }}\"
                        }
                      ]
                    }
                  ]
                },
                \"issuetype\": {
                  \"name\": \"Task\"
                },
                \"parent\": {
                  \"key\": \"${{ steps.issue-parser.outputs.issueparser_parentKey }}\"
                }
              }
            }")

          echo "$RESPONSE"

          ISSUE_KEY=$(echo "$RESPONSE" | jq -r '.key')

          echo "issue=$ISSUE_KEY" >> $GITHUB_OUTPUT

      - name: Log created issue
        run: |
          echo "Created Jira Issue: ${{ steps.create-jira.outputs.issue }}"

      - name: Create branch with Ticket number
        run: |
          git config --global user.name github-actions
          git config --global user.email github-actions@github.com

          git fetch origin dev
          git checkout -b ${{ steps.create-jira.outputs.issue }} origin/dev
          git push origin ${{ steps.create-jira.outputs.issue }}

      - name: Update issue title
        uses: actions-cool/issues-helper@v3
        with:
          actions: "update-issue"
          token: ${{ secrets.GITHUB_TOKEN }}
          title: "[${{ steps.create-jira.outputs.issue }}] ${{ github.event.issue.title }}"

      - name: Add comment with Jira issue link
        uses: actions-cool/issues-helper@v3
        with:
          actions: "create-comment"
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          body: |
            Jira Issue Created:
            [${{ steps.create-jira.outputs.issue }}](
            ${{ secrets.JIRA_BASE_URL }}/browse/${{ steps.create-jira.outputs.issue }})
```
